CREATE TABLE IF NOT EXISTS `mc_characters` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `character_id` varchar(96) NOT NULL,
  `license` varchar(64) NOT NULL,
  `slot` tinyint unsigned NOT NULL,
  `firstname` varchar(64) NOT NULL,
  `lastname` varchar(64) NOT NULL,
  `sex` varchar(8) NOT NULL,
  `birthdate` date NOT NULL,
  `nationality` varchar(32) NOT NULL,
  `job` varchar(64) NOT NULL DEFAULT 'unemployed',
  `job_grade` int NOT NULL DEFAULT 0,
  `money` int NOT NULL DEFAULT 0,
  `bank` int NOT NULL DEFAULT 0,
  `skin` longtext DEFAULT NULL,
  `metadata` longtext DEFAULT NULL,
  `pos_x` double NOT NULL DEFAULT 0,
  `pos_y` double NOT NULL DEFAULT 0,
  `pos_z` double NOT NULL DEFAULT 0,
  `heading` double NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_character_id` (`character_id`),
  UNIQUE KEY `uniq_license_slot` (`license`, `slot`),
  KEY `idx_license` (`license`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
